spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/neohoon
    username: root
    password: 1234
  mvc:
    view:
      prefix:
      suffix:
  web:
    resources:
      add-mappings: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    enabled-protocols: TLSv1.1,TLSv1.2

neohoon:
  security:
    cors:
      allowed-origins: "http://localhost:5173"
    auth:
      jwt:
        secret: ENC(lly70WjFjzPZMTuepxQrmNv7R9BDa/K4R91foRqQwJin/D2RsNhgPWJ8Mh63bOXeBDIg8SI6y7hvSvItcZ2mvdDJg9rExEnaKa+DbxihtCB7QEgtafBq2QJFG/knMse6Blj75iYem7wZC+1BANsi4uiSaMnv+1zgJCrNHNmaNyYbIPXTvfZ8tCzrSS3/KMDWpcvkHk3fw9zaXVoiIe9rWMpZ3+CTc0okWEQrHX+h+y9mIVYt8iqfUMRdiZIfW+tE1gp8xSYkC6rMExIhLbC7Ur+ZO3DikagdUJrb0D6sM1dJ6C4+WQDKpptjbphkbgIhVoXPmkv3pnXR+6BctHgtAZJZ6wAXcUg2wc4Y8J0/tlU=)
  api:
    version: v1
logging:
  level:
    com.neohoon: debug
