spring:
  docker:
    compose:
      file: api/compose.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(siUK0Q5HEB00uMGGRyfGiqt0HuDVuSWC/fU7MkZ1FXtCozX7KiB4GUJGBsMZn2VS)
            client-secret: ENC(vYx6Uq4rnzetqrxV7wVBDvzRHNwedE0v4BQPOwVi4ys19ZyZdYqaojmnhMVz7MnQ)
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
          naver:
            client-id: ENC(BPcCQMvlaocBGPCLOqsZZxZMMHpPecOUUV0FfSvQ0zQ=)
            client-secret: ENC(tJmAYYCd7AJNptCkn3zis0Od2yVgi/Ke)
            redirect-uri: https://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  web:
    resources:
      add-mappings: false

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store: api/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    enabled-protocols: TLSv1.1,TLSv1.2
  servlet:
    session:
      cookie:
        name: nhsid

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    string-output-type: base64

neohoon:
  security:
    cors:
      allowed-origins: ""
    auth:
      expire-day: 14
      jwt:
        secret: ENC(lly70WjFjzPZMTuepxQrmNv7R9BDa/K4R91foRqQwJin/D2RsNhgPWJ8Mh63bOXeBDIg8SI6y7hvSvItcZ2mvdDJg9rExEnaKa+DbxihtCB7QEgtafBq2QJFG/knMse6Blj75iYem7wZC+1BANsi4uiSaMnv+1zgJCrNHNmaNyYbIPXTvfZ8tCzrSS3/KMDWpcvkHk3fw9zaXVoiIe9rWMpZ3+CTc0okWEQrHX+h+y9mIVYt8iqfUMRdiZIfW+tE1gp8xSYkC6rMExIhLbC7Ur+ZO3DikagdUJrb0D6sM1dJ6C4+WQDKpptjbphkbgIhVoXPmkv3pnXR+6BctHgtAZJZ6wAXcUg2wc4Y8J0/tlU=)
        validity-in-seconds: 5
  front:
    target: http://localhost:5173
  api:
    version: v1
logging:
  level:
    com.neohoon: debug
