spring:
  docker:
    compose:
      file: api/compose.yaml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 500
        one-indexed-parameters: true
        size-parameter: pageSize
        page-parameter: pageNum