spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://mysql:3306/neohoon?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix:
      suffix:
  web:
    resources:
      add-mappings: false
server:
  http2:
    enabled: true

neohoon:
  security:
    cors:
      allowed-origins: ""
    auth:
      jwt:
        secret: ENC(skjfQ534kaYzuVEpxzv+ZAK4M87C+nwVOO7r/ITBP2i1yf/+WM6K2RMGAjx338HBzCmTwPrFNHRxJkFxr1QRxYy80+wKjzHXsJ7FaTSRLB65R1qBN65ScHme0gUhA3Ugm9UCwMJjodAkZL+MCGCfQSE7+dPofh7myk6Mn0beZvPlu4ks6QltnY0AiIUWxYWfM+In31A6YijpI9RX+2CSsmPqGG9QbGxczDlTd/aEe6D67Z5vFe8OmUxBEU6JZJkwwzlrlvkMQKSt2B0ddM1R0R9XzBYcBXj6ZnnTevP59Fc4Xh15xgbcPbVqPRq+Gx4pwn85f6NrO2/b5lmQBqgDe+S0prkBzKwjVSISsrBhYaQ=)
  api:
    version: v1

logging:
  level:
    com.neohoon: debug

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: threaddump, heapdump
info:
  contact:
    email: kkkqwerasdf123@naver.com
