spring:
  datasource:
    url: jdbc:mysql://mysql:3306/neohoon?characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      host: neohoon-redis
      port: 6379
  mvc:
    view:
      prefix:
      suffix:
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(siUK0Q5HEB00uMGGRyfGiqt0HuDVuSWC/fU7MkZ1FXtCozX7KiB4GUJGBsMZn2VS)
            client-secret: ENC(vYx6Uq4rnzetqrxV7wVBDvzRHNwedE0v4BQPOwVi4ys19ZyZdYqaojmnhMVz7MnQ)
            redirect-uri: https://drumtong.neohoon.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
          naver:
            client-id: ENC(BPcCQMvlaocBGPCLOqsZZxZMMHpPecOUUV0FfSvQ0zQ=)
            client-secret: ENC(tJmAYYCd7AJNptCkn3zis0Od2yVgi/Ke)
            redirect-uri: https://drumtong.neohoon.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  http2:
    enabled: true

neohoon:
  security:
    cors:
      allowed-origins: ""
    auth:
      jwt:
        secret: ENC(skjfQ534kaYzuVEpxzv+ZAK4M87C+nwVOO7r/ITBP2i1yf/+WM6K2RMGAjx338HBzCmTwPrFNHRxJkFxr1QRxYy80+wKjzHXsJ7FaTSRLB65R1qBN65ScHme0gUhA3Ugm9UCwMJjodAkZL+MCGCfQSE7+dPofh7myk6Mn0beZvPlu4ks6QltnY0AiIUWxYWfM+In31A6YijpI9RX+2CSsmPqGG9QbGxczDlTd/aEe6D67Z5vFe8OmUxBEU6JZJkwwzlrlvkMQKSt2B0ddM1R0R9XzBYcBXj6ZnnTevP59Fc4Xh15xgbcPbVqPRq+Gx4pwn85f6NrO2/b5lmQBqgDe+S0prkBzKwjVSISsrBhYaQ=)
        validity-in-seconds: 5
  front:
    target: https://drumtong.neohoon.com
  api:
    version: v1

logging:
  level:
    com.neohoon: debug

management:
  endpoints:
    web:
      exposure:
        include: health
        exclude: threaddump, heapdump
info:
  contact:
    email: kkkqwerasdf123@naver.com
